### ISSUE TITLE
Possible Duplicate ID

### ISSUE THREAD

**Issue by ghost** [ddalki1205/registration_system#4]
The function regarding adding a student to the program in `add_student.py`

```
def create(self, attributes):
        name, age, student_id, email, phone = attributes
        new_student = self.constructor(name, age, student_id, email, phone)
        self.func(new_student)
```

There is no guard clause or conditions for checking if the student exist as it immediately calls the write function. Refactoring the codebase would solve future issues, however, working within these constrains...

**Solution:**
when reading students from file, store in array and check every student if the id matches the newly created one to prevent writing to file if it passes

**Comment by iya5** [comment]
merging pull request
